[package]
name = "space_worm"
version = "0.5.0"
edition = "2021"

[dependencies]
minifb = "0.28.0"
image = "0.25.6"
winit = "0.27.0"
rodio = { version = "0.17", features = ["mp3"] }
rand = "0.9.1"

[[bin]]
name = "space_worm"
path = "src/main.rs"

